import 'package:kingdom_heir/features/bible/domain/entities/bible_local_state.dart';

/// Curated catalogue of reading plans. Lives in code so it can ship without
/// a network call. Each plan's `chapters` list is intentionally short and
/// representative — full-length plans would normally come from a CMS.
class BibleReadingPlansCatalog {
  const BibleReadingPlansCatalog._();

  static final List<BibleReadingPlan> all = [
    const BibleReadingPlan(
      id: 'gospel_in_7',
      title: 'The Gospel in 7 Days',
      subtitle: 'John through Romans',
      description: 'Trace the message of salvation from the words of Jesus to '
          "Paul's most pastoral letter.",
      durationDays: 7,
      icon: 'auto_awesome',
      accentHex: '#D4AF37',
      coverEmoji: '✦',
      chapters: [
        'JHN.1',
        'JHN.3',
        'JHN.14',
        'ACT.2',
        'ROM.3',
        'ROM.5',
        'ROM.8',
      ],
    ),
    const BibleReadingPlan(
      id: 'psalms_for_the_soul',
      title: 'Psalms for the Soul',
      subtitle: '21 days of worship',
      description:
          'A three-week journey through the most loved songs in Scripture — '
          'for lament, joy, and everything between.',
      durationDays: 21,
      icon: 'music_note',
      accentHex: '#7CE3B5',
      coverEmoji: '♪',
      chapters: [
        'PSA.1',
        'PSA.8',
        'PSA.19',
        'PSA.23',
        'PSA.27',
        'PSA.34',
        'PSA.46',
        'PSA.51',
        'PSA.63',
        'PSA.84',
        'PSA.91',
        'PSA.100',
        'PSA.103',
        'PSA.107',
        'PSA.119.1',
        'PSA.121',
        'PSA.130',
        'PSA.139',
        'PSA.145',
        'PSA.146',
        'PSA.150',
      ],
    ),
    const BibleReadingPlan(
      id: 'wisdom_in_proverbs',
      title: 'Wisdom in Proverbs',
      subtitle: '30 days of practical wisdom',
      description: 'One chapter a day. Let the Proverbs reshape how you speak, '
          'work, and love.',
      durationDays: 30,
      icon: 'diamond',
      accentHex: '#FFD166',
      coverEmoji: '◆',
      chapters: [
        'PRO.1',
        'PRO.2',
        'PRO.3',
        'PRO.4',
        'PRO.5',
        'PRO.6',
        'PRO.7',
        'PRO.8',
        'PRO.9',
        'PRO.10',
        'PRO.11',
        'PRO.12',
        'PRO.13',
        'PRO.14',
        'PRO.15',
        'PRO.16',
        'PRO.17',
        'PRO.18',
        'PRO.19',
        'PRO.20',
        'PRO.21',
        'PRO.22',
        'PRO.23',
        'PRO.24',
        'PRO.25',
        'PRO.26',
        'PRO.27',
        'PRO.28',
        'PRO.29',
        'PRO.30',
        'PRO.31',
      ],
    ),
    const BibleReadingPlan(
      id: 'jesus_in_40_days',
      title: 'Jesus in 40 Days',
      subtitle: 'Walk with Christ through the Gospels',
      description:
          'Forty readings across Matthew, Mark, Luke and John that follow '
          "the Father's son from the cradle to the cross.",
      durationDays: 40,
      icon: 'wb_sunny',
      accentHex: '#FF6B8A',
      coverEmoji: '☀',
      chapters: [
        'MAT.1',
        'MAT.5',
        'MAT.6',
        'MAT.7',
        'MAT.13',
        'MAT.18',
        'MAT.25',
        'MAT.28',
        'MRK.1',
        'MRK.4',
        'MRK.8',
        'MRK.10',
        'MRK.13',
        'MRK.16',
        'LUK.1',
        'LUK.2',
        'LUK.4',
        'LUK.6',
        'LUK.10',
        'LUK.15',
        'LUK.19',
        'LUK.22',
        'LUK.24',
        'JHN.1',
        'JHN.2',
        'JHN.3',
        'JHN.4',
        'JHN.5',
        'JHN.6',
        'JHN.9',
        'JHN.10',
        'JHN.11',
        'JHN.13',
        'JHN.14',
        'JHN.15',
        'JHN.17',
        'JHN.18',
        'JHN.19',
        'JHN.20',
        'JHN.21',
      ],
    ),
    const BibleReadingPlan(
      id: 'kingdom_heirs_foundations',
      title: 'Kingdom Foundations',
      subtitle: '7 days, identity in Christ',
      description:
          'A one-week companion plan for new believers. Identity, family, '
          'mission, and the Word.',
      durationDays: 7,
      icon: 'foundation',
      accentHex: '#9CC4FF',
      coverEmoji: '✝',
      chapters: [
        'GEN.1',
        'PSA.23',
        'ISA.53',
        'MAT.5',
        'JHN.3',
        'ROM.8',
        'GAL.5',
      ],
    ),
  ];

  static BibleReadingPlan byId(String id) =>
      all.firstWhere((p) => p.id == id, orElse: () => all.first);
}
