import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:kingdom_heir/core/theme/app_colors.dart';
import 'package:kingdom_heir/core/theme/app_spacing.dart';
import 'package:kingdom_heir/core/theme/app_typography.dart';
import 'package:kingdom_heir/core/widgets/app_button.dart';
import 'package:kingdom_heir/core/widgets/app_text_field.dart';
import 'package:kingdom_heir/features/prayer_requests/data/models/prayer_request_model.dart';
import 'package:kingdom_heir/features/prayer_requests/presentation/providers/prayer_provider.dart';

const _categories = [
  'General',
  'Healing',
  'Provision',
  'Salvation',
  'Relationships',
  'Deliverance',
  'Direction',
  'Thanksgiving',
];

const _visibilityOptions = [
  'Public — anyone can see',
  'Leaders only — visible to church leaders',
  'Private — only you can see',
];

class SubmitPrayerScreen extends ConsumerStatefulWidget {
  const SubmitPrayerScreen({super.key});

  @override
  ConsumerState<SubmitPrayerScreen> createState() => _SubmitPrayerScreenState();
}

class _SubmitPrayerScreenState extends ConsumerState<SubmitPrayerScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _bodyController = TextEditingController();
  int _selectedCategory = 0;
  int _selectedVisibility = 0;
  bool _isAnonymous = false;

  @override
  void dispose() {
    _titleController.dispose();
    _bodyController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!(_formKey.currentState?.validate() ?? false)) return;

    final visibilityMap = ['public', 'leaders_only', 'private'];

    final model = PrayerRequestModel(
      id: '', // Generated by Supabase
      authorId: '', // Filled by repo
      title: _titleController.text.trim(),
      body: _bodyController.text.trim(),
      category: _categories[_selectedCategory],
      visibility: visibilityMap[_selectedVisibility],
      isAnonymous: _isAnonymous,
      status: 'active',
      prayerCount: 0,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    await ref.read(submitPrayerProvider.notifier).submit(model.toInsertJson());

    if (mounted) {
      final error = ref.read(submitPrayerProvider).error;
      if (error != null) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $error')),
        );
      } else {
        context.pop();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('🙏 Your prayer request has been submitted.'),
            backgroundColor: AppColors.success,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isLoading = ref.watch(submitPrayerProvider).isLoading;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Submit Prayer Request'),
        leading: const BackButton(),
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(AppSpacing.lg),
          children: [
            // ── Header ────────────────────────────────────────────────
            Container(
              padding: const EdgeInsets.all(AppSpacing.lg),
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [AppColors.navy, AppColors.navyMid],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                ),
                borderRadius: BorderRadius.circular(AppSpacing.radiusLg),
              ),
              child: Row(
                children: [
                  const Icon(
                    Icons.self_improvement_rounded,
                    color: AppColors.gold,
                    size: 32,
                  ),
                  const SizedBox(width: AppSpacing.md),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Share your heart',
                          style: AppTypography.textTheme.titleMedium?.copyWith(
                            color: AppColors.white,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                        Text(
                          'The church is standing with you in prayer.',
                          style: AppTypography.textTheme.bodySmall
                              ?.copyWith(color: Colors.white70),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ).animate().fadeIn(),

            const SizedBox(height: AppSpacing.xl),

            // ── Category selector ─────────────────────────────────────
            Text('Category', style: AppTypography.textTheme.titleSmall),
            const SizedBox(height: AppSpacing.sm),
            Wrap(
              spacing: AppSpacing.sm,
              runSpacing: AppSpacing.sm,
              children: _categories.asMap().entries.map((e) {
                final i = e.key;
                final label = e.value;
                final isSelected = i == _selectedCategory;
                return FilterChip(
                  label: Text(label),
                  selected: isSelected,
                  onSelected: (_) => setState(() => _selectedCategory = i),
                  selectedColor: AppColors.gold.withValues(alpha: 0.15),
                  checkmarkColor: AppColors.goldDark,
                  side: BorderSide(
                    color: isSelected ? AppColors.gold : theme.dividerColor,
                  ),
                  labelStyle: AppTypography.textTheme.labelSmall?.copyWith(
                    fontWeight: isSelected ? FontWeight.w700 : FontWeight.w400,
                    color: isSelected ? AppColors.goldDark : null,
                  ),
                );
              }).toList(),
            ).animate().fadeIn(delay: 100.ms),

            const SizedBox(height: AppSpacing.xl),

            // ── Title ─────────────────────────────────────────────────
            AppTextField(
              controller: _titleController,
              label: 'Prayer title',
              hint: 'Brief description of your request',
              prefixIcon: Icons.title_rounded,
              isRequired: true,
              validator: (v) =>
                  (v?.isEmpty ?? true) ? 'Please add a title' : null,
            ).animate().fadeIn(delay: 150.ms),

            const SizedBox(height: AppSpacing.lg),

            // ── Body ──────────────────────────────────────────────────
            AppTextField(
              controller: _bodyController,
              label: 'Your prayer request',
              hint: "Share the details of what you're believing God for...",
              maxLines: 6,
              minLines: 4,
              isRequired: true,
              validator: (v) =>
                  (v?.isEmpty ?? true) ? 'Please describe your request' : null,
            ).animate().fadeIn(delay: 200.ms),

            const SizedBox(height: AppSpacing.xl),

            // ── Visibility ────────────────────────────────────────────
            Text('Visibility', style: AppTypography.textTheme.titleSmall),
            const SizedBox(height: AppSpacing.sm),
            AppRadioGroup<int>(
              options: List.generate(_visibilityOptions.length, (i) => i),
              labels: _visibilityOptions,
              value: _selectedVisibility,
              onChanged: (v) => setState(() => _selectedVisibility = v ?? 0),
            ).animate().fadeIn(delay: 250.ms),

            const SizedBox(height: AppSpacing.lg),

            // ── Anonymous ─────────────────────────────────────────────
            Card(
              margin: EdgeInsets.zero,
              child: SwitchListTile(
                title: const Text('Submit anonymously'),
                subtitle: const Text('Your name will be hidden from others'),
                value: _isAnonymous,
                onChanged: (v) => setState(() => _isAnonymous = v),
                activeThumbColor: AppColors.ink,
                activeTrackColor: AppColors.gold,
              ),
            ).animate().fadeIn(delay: 300.ms),

            const SizedBox(height: AppSpacing.xxxl),

            // ── Submit ────────────────────────────────────────────────
            AppButton(
              label: 'Submit Prayer Request',
              icon: Icons.send_rounded,
              isLoading: isLoading,
              onPressed: isLoading ? null : _submit,
            ).animate().fadeIn(delay: 350.ms),

            const SizedBox(height: AppSpacing.lg),

            Text(
              'By submitting, you agree that this request may be seen '
              'by church members according to your visibility setting.',
              style: AppTypography.textTheme.bodySmall?.copyWith(
                color: theme.colorScheme.onSurface.withValues(alpha: 0.45),
              ),
              textAlign: TextAlign.center,
            ),
          ],
        ),
      ),
    );
  }
}
